#ifndef EEZ_LVGL_UI_VARS_H
#define EEZ_LVGL_UI_VARS_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// enum declarations

// Flow global variables

enum FlowGlobalVariables {
    FLOW_GLOBAL_VARIABLE_LIVE_SCAN_TAB = 0,
    FLOW_GLOBAL_VARIABLE_SCAN3D_TAB = 1,
    FLOW_GLOBAL_VARIABLE_SETTINGS = 2,
    FLOW_GLOBAL_VARIABLE_IS_AUTO_SCAN_PANEL_HIDDEN = 3,
    FLOW_GLOBAL_VARIABLE_STEPS_COUNT = 4,
    FLOW_GLOBAL_VARIABLE_SECONDS_COUNT = 5,
    FLOW_GLOBAL_VARIABLE_IS_AUTO_SCAN_PROCESS_PANEL_HIDDEN = 6,
    FLOW_GLOBAL_VARIABLE_IS_MANUAL_SCAN_PROCESS_PANEL_HIDDEN = 7,
    FLOW_GLOBAL_VARIABLE_IS_SENS_LIST_DISABLED = 8,
    FLOW_GLOBAL_VARIABLE_IS_LOW_BATT_PANEL_HIDDEN = 9,
    FLOW_GLOBAL_VARIABLE_IS_BATT_PIC_HIDDEN = 10,
    FLOW_GLOBAL_VARIABLE_IS_MAIN_PANEL_HIDDEN = 11,
    FLOW_GLOBAL_VARIABLE_IS_LOG_TEXT_HIDDEN = 12,
    FLOW_GLOBAL_VARIABLE_IS_CALIB_BUTTON_HIDDEN = 13,
    FLOW_GLOBAL_VARIABLE_IS_PROGRESS_BAR_HIDDEN = 14
};

// Native global variables

#ifdef __cplusplus
}
#endif

#endif /*EEZ_LVGL_UI_VARS_H*/